-- Create VOCAB_DEFINITION table--

DROP TABLE IF EXISTS VOCAB_DEFINITION;

CREATE TABLE VOCAB_DEFINITION (
 VOCAB_DEFINITION_ID INTEGER PRIMARY KEY,
 PARTS_OF_SPEECH TEXT NOT NULL,
 DEFINITION TEXT  NOT NULL UNIQUE,
 EXAMPLE TEXT
);

-- Create DIFFICULTY table--

DROP TABLE IF EXISTS DIFFICULTY;

CREATE TABLE DIFFICULTY (
 DIFFICULTY_ID INTEGER PRIMARY KEY,
 DIFFICULTY_LEVEL INTEGER NOT NULL UNIQUE,
 DESCRIPTION TEXT NOT NULL
);

-- Create VOCAB_WORD table--

DROP TABLE IF EXISTS VOCAB_WORD;

CREATE TABLE VOCAB_WORD (
 VOCAB_WORD_ID INTEGER PRIMARY KEY,
 WORD TEXT  NOT NULL UNIQUE,
 DIFFICULTY_ID TEXT NOT NULL,
 FOREIGN KEY(DIFFICULTY_ID) REFERENCES DIFFICULTY(DIFFICULTY_ID)
);

CREATE INDEX IX_VOCAB_WORD_DIFFICULTY_ID on VOCAB_WORD(DIFFICULTY_ID);

-- Create VOCAB table--

DROP TABLE IF EXISTS VOCAB;

CREATE TABLE VOCAB (
 VOCAB_ID INTEGER PRIMARY KEY,
 VOCAB_WORD_ID INTEGER NOT NULL UNIQUE,
 VOCAB_DEFINITION_ID INTEGER NOT NULL UNIQUE,
 FOREIGN KEY(VOCAB_WORD_ID) REFERENCES VOCAB_WORD(VOCAB_WORD_ID),
 FOREIGN KEY(VOCAB_DEFINITION_ID) REFERENCES VOCAB_DEFINITION(VOCAB_DEFINITION_ID)
);

CREATE INDEX IX_VOCAB_VOCAB_WORD_ID on VOCAB(VOCAB_WORD_ID);
CREATE INDEX IX_VOCAB_VOCAB_DEFINITION_ID on VOCAB(VOCAB_DEFINITION_ID);